// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szaxmllftjhpzovccjwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6YXhtbGxmdGpocHpvdmNjandmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTgzMjQsImV4cCI6MjA3MDIzNDMyNH0.A7wcdbbexBCYjmiJu9t4ww8flmqgU0jRI92zc3bxPG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});